---
title: "Fish Density 2017-2018: Prose"
author: "Sean Kinard"
date: "2023-02-06"
output: 
  pdf_document: 
    fig_caption: yes
editor_options: 
  markdown: 
    wrap: 72
---

\newpage

## Figure 1 - Density vs Rainfall: Boxplot
In 2017, densities across the region were about 100m^-2^. Densities at San Fernando varied the most after the hurricane followed by Perdido and Placedo.

In 2018, densities were greatest at drier sites, and declined with rainfall. However, East Mustang (and Perdido to a lesser extent) countered the rainfall trend.

In 2020, only 4 samples were taken, but the Mustang sites emerged below average. The relationship between density and rainfall observed in 2018 is less apparent. Mission and Perdido also had below average densities of fish. So several dry sites and Placedo had above average densities in 2020.

## Figure 2 - Density vs Diatom Concentration
In 2017 and 2020, there is an apparent positive relationship between fish density and diatoms. However, this pattern is not apparent in 2018.

## Figure 3 - Density vs 2-Week Maximum Discharge
In 2017 (and 2018 less so perhaps), maximum discharge in the 2 weeks prior to sampling is negatively related to densities of fish.

## Figure 4 - Density vs Nitrate Concentrations
In all sampling periods, nitrate concentrations are positively related to fish densities.

## Figure 5 - Density vs Time: Community 
In 2017, fish communities across the region experienced a shortlived bump in fish density before falling (slowly at some sites, and precipitously at others) to a low trough in the mid summer of 2018. Similarly, in 2020, densities start high in January and reach a minimum in mid-summer. Fish densities appear to recover in the 3rd or 4th quarter of the year.

## Figure 6 - Density vs Time: Families 
In 2017 most family experienced a recovery or seasonal bump after hurricane Harvey.

In 2018 and 2020, there are no obvious patterns in density within families across time. However, poeciliids peak in the late 4th quarter and early 1st quarter across all sampling periods.

## Figure 7 - Density vs Time: Small-Gape, Deep-Bodied Taxa 
Within small-gaped deep-bodied fish, most species maintain stable densities through time. *L.megalotis* densities had the most apparent recovery bump after hurricane Harvey and dipped slightly in the mid-summer of 2018.

## Figure 8 - Density vs Time: Large-Gape, Deep-Bodied Fish 
Large-gaped, deep-bodied fish remain in low densities (~1) through time, and may be better suited for binary (present-absent) types of analyses.

## Figure 9 - Density vs Time: Poeciliidae 
Poeciliid densities peak in the 4th and 1st quarters of the year.

## Figure 10 - Density vs Rainfall: Regression Community 
Fish densities decline with annual rainfall, but the pattern was weakest in 2017 (immediately after the hurricane).

## Figure 11 - Density vs Rainfall: Regression Centrarchid 
The most abundant centrarchids include longear sunfish (*L.megalotis*) and (*L.macrochirus*). Longear sunfish are most abundant at wetter sites, and densities decline across the gradient towards the drier sites. In contrast, bluegill sunfish are more abundant at the dry sites and decline as climate becomes more humid. Green sunfish (*L.cyanellus*) and redbreast sunfish (*L.auritus*) and large-mout bass (*M.salmoides*) appear to peak in densities at the transition sites near the middle of the rainfall gradient. 

In 2017, the positive relationship between longear densities and rainfall was extreme compared to 2018 and 2020.

## Figure 12 - Density vs Rainfall: Regression Poeciliid 
In 2017, western mosquitofish (*G. affinis*) densities had a  weak (*p*~0.1), positive relationship with rainfall. In 2018 and 2020, mosquitofish densities remained similar across the study region.

In contrast, salifin mollies (*P. latipinna*) were negatively related to rainfall in all sampling periods, becoming absent East of Placedo.
