# RDA_figures
# Sean Kinard
# 1-28-2023

#------------------------------------------------------------------------------
# Tidy data
#------------------------------------------------------------------------------

# load data
d100 <- read_csv('Data/fish_d100.csv')
bm <- read_csv('Data/fish_biomass_megaframe.csv')
ste <- read_csv('Data/site_daily_nogap.csv')
lte <- read_csv('Data/site_longterm_nogap.csv')

# my environmental variables
my_evars <- c('annualrain', 'flsh', 'lfpp', 'hfpp3',
              'q_2w_max', 'depth_mx', 'silt, gravel',
              'total_algae', 'canopy_density_mid',
              'conductivity', 'do_mg_l',
              'nh4_n', 'no3n', 'ortho_p')

DC <- d100 %>%
  mutate(taxon = str_replace_all(lowest_taxon, ' ', '')) %>%
  select(site_code, collection_date, taxon, d100_spe) %>%
  left_join(lte) %>%
  left_join(ste) %>%
  pivot_wider(names_from = taxon,
              values_from = d100_spe,
              values_fill = 0)

DB <- bm %>%
  mutate(taxon = paste(substr(str_to_title(genus),1,1),
                       species,
                       sep='.'  ) ) %>%
  mutate(biomass = ceiling(biomass*100)) %>%
  select(site_code, collection_date, taxon, biomass) %>%
  distinct() %>%
  left_join(lte) %>%
  left_join(ste) %>%
  pivot_wider(names_from = taxon,
              values_from = biomass,
              values_fill = 0)

# year-specific data frames
DC_17 <- filter(DC, collection_date < ymd('2018-01-01')) 
DC_18 <- filter(DC, collection_date < ymd('2019-01-01') &
  collection_date > ymd('2018-01-01') )
DC_20 <- filter(DC, collection_date < ymd('2021-01-01') &
  collection_date > ymd('2020-01-01') )

DB_17 <- filter(DB, collection_date < ymd('2018-01-01')) 
DB_18 <- filter(DB, collection_date < ymd('2019-01-01')  &
  collection_date > ymd('2018-01-01') )
DB_20 <- filter(DB, collection_date < ymd('2021-01-01') &
  collection_date > ymd('2020-01-01') )


#------------------------------------------------------------------------------
# RDA_input functions
#------------------------------------------------------------------------------
# functions
spec_filter <- function(my_data) {
  my_data %>%
    mutate(UID = paste(site_code, collection_date, sep='_')) %>%
    column_to_rownames("UID") %>%
    select(c('L.cyanellus' : 'O.aureus'))
}
env_filter <- function(my_data) {
  my_data %>%
  mutate(UID = paste(site_code, collection_date, sep='_')) %>%
  column_to_rownames("UID") %>%
  mutate(total_algae = sum(green_algae, diatoms,bluegreen_cyano)) %>%
  select(any_of(my_evars)) }

#------------------------------------------------------------------------------
# RDA function
#------------------------------------------------------------------------------
# function runs RDA and creates a list of data frames for plots and tables
my_rda <- function(d_env, d_spec) {
# step 1: The ordiplot object is obtained from the result of via function rda. The ordination is done with a community data set that is transformed by the Hellinger method.
# script generated by the BiodiversityR GUI from the constrained ordination menu
fish_hell <- disttransform(d_spec, method='hellinger')
Ord_model <- rda(fish_hell ~ . ,data=d_env, scaling="species")
# This can be plotted via ordiplot
plot2 <- ordiplot(Ord_model, choices=c(1,2))
#------------------------------------------------------------------------------
# Step 2 : To plot data via ggplot2
# Extract information on the locations of sites (circles in the ordiplot)
sites_long <- sites.long(plot2, env.data=d_env) %>%
  mutate(site_code = substr(rownames(d_env), 1,2),
         collection_date = substr(rownames(d_env), 4,13),
         collection_date = ymd(collection_date),
         cd = collection_date) %>%
  separate(cd, into=c('year', 'month', 'day'), sep='-')
# Extract species info
species_long <- species.long(plot2)
# Information on the labeling of the axes is obtained with function axis.long. This information is extracted from the ordination model and not the ordiplot, hence it is important to select the same axes via argument 'choices'. The extracted information includes information on the percentage of explained variation. Be advised to cross-check with the summary of the redundancy analysis, where information on proportion explained is given.
axis_long <- axis.long(Ord_model, choices=c(1, 2))
#------------------------------------------------------------------------------
# fit species vectors
spp_fit <- envfit(plot2, env=fish_hell)
df_spp_fit <- data.frame(r=spp_fit$vectors$r, p=spp_fit$vectors$pvals)
spec_vector_long <- species.long(plot2, spec.data=df_spp_fit)
RDA_sv <- spec_vector_long[spec_vector_long$p < 0.05, ]

# fit environmental vectors
vectors.envfit <- envfit(plot2, env= d_env)
vectors.long2 <- filter(vectorfit.long(vectors.envfit), p < 0.05)
RDA_ev <- vectors.long2[vectors.long2$p <= 0.05, ]
#------------------------------------------------------------------------------
# Table
RDA_table <- species_long %>%
  dplyr::rename(vector = labels) %>%
  full_join(vectors.long2) %>% 
  filter(p < 0.05) %>%
  mutate(r = round(r, 3),
         p = round(p, 3),
         axis1 = round(axis1, 3),
         axis2 = round(axis2, 3)) %>%
  select(vector, r, p, axis1, axis2) %>%
  dplyr::rename('p-value'=p, 'Axis-1'=axis1, 'Axis-2'=axis2, Vector=vector)

# ---------------------------------------------------------------------------
# Format time variables
sites_long <- sites_long %>%
  mutate(cd2 = collection_date) %>%
  separate(cd2, into = c('year', 'month', 'day')) %>%
  mutate(year=as.numeric(year),
         month=as.numeric(month),
         day=as.numeric(day)) %>%
  mutate(nday=month*30+day) %>%
  mutate(qtr = ifelse(month < 4, 'Q1',
                      ifelse(month > 3 & month < 7, 'Q2',
                             ifelse(month > 6 & month < 10, 'Q3', 'Q4')))) %>%
  mutate(days_to_hh = 
           as.numeric(as_date(collection_date) - ymd('2017-08-27')) ) %>%
  mutate(weeks_to_hh = ceiling(days_to_hh/7),
         months_to_hh = round(days_to_hh/30, 0)) %>%
  mutate(site_week_label = paste(site_code, weeks_to_hh, sep="-"))
# -----------------------------------------------------------------------
# Calculate all-time centroid for each site
mycent_alltime <-  sites_long %>%
  group_by(annualrain) %>%
  dplyr::summarize(axis1_mu = mean(axis1),
                   axis2_mu = mean(axis2),
                   axis1_upr = quantile(axis1, probs=.9),
                   axis1_lwr = quantile(axis1, probs=.1),
                   axis2_upr = quantile(axis2, probs=.9),
                   axis2_lwr = quantile(axis2, probs=.1))

labs_alltime <- mycent_alltime %>%
  select(annualrain, axis1_mu, axis2_mu) %>%
  left_join(sites_long %>%
              select(annualrain, site_code)) %>%
  mutate(annualrain_label = paste(round(annualrain, 0), 'mm', sep=' ')) %>%
  unique()
# -----------------------------------------------------------------------
RDA_out <- list(axis_long,
                sites_long,
                species_long,
                RDA_ev,
                RDA_sv,
                RDA_table,
                mycent_alltime,
                labs_alltime)

return(RDA_out) }

#------------------------------------------------------------------------------
# species ordination plot function
#------------------------------------------------------------------------------
# With an ordination via redundancy analysis, the positions of species should be interpreted as arrows. It is straightforward to show the positions of the species as arrows. However, with a large number of species, it is better to reduce the number to those that explain more of the variation among the sites. This information is obtained with the envfit function of vegan.

RDA_spe <- function(rda_out) {
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble()
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()

  # ---------------------------------------------------------------------------
  # Species Plot
  ggplot() +
    stat_ellipse(data = sites_long,
                 aes(x=axis1, y=axis2, fill = as.factor(annualrain)),
                 geom='polygon', alpha=.2, level = 0.9,show.legend = F)+
    #geom_rect(aes(ymin=axis2_lwr, ymax=axis2_upr,
    #              xmin=axis1_lwr, xmax=axis1_upr,
    #              fill=annualrain),
    #          data= mycent_alltime, 
    #          color=NA, alpha = .25) +
    geom_label(aes(label=annualrain_label,
                   x=axis1_mu, y=axis2_mu, fill=as.factor(annualrain)),
               data= labs_alltime, ) +
    geom_point(data=species_long,
               aes(x=axis1, y=axis2), 
               fill = 'white', shape = 24, size = 2) +
    geom_label_repel(data=RDA_sv,
                     aes(x=axis1, y=axis2, label=labels),
                     colour="white", fill = 'grey15', box.padding = .9,
                     max.overlaps = 15) +
    xlab(axis_long[1, "label"]) +
    ylab(axis_long[2, "label"]) +
    scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_fill_manual(values = my_colors) +
    scale_color_manual(values=my_colors) +
    #paletteer::scale_fill_paletteer_c("grDevices::Zissou 1", direction=-1) +
    #paletteer::scale_color_paletteer_c("grDevices::Zissou 1", direction =-1) +
    coord_fixed(ratio=1) +
    theme_dark(base_size = 12) +
    theme(legend.position = 'none')
    }

#------------------------------------------------------------------------------
# environment ordination plot function
#------------------------------------------------------------------------------
RDA_env <- function(rda_out) {
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble()
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()
  
  # e-labels
  RDA_ev <- RDA_ev %>%
    mutate(my_label = str_to_title(vector)) %>%
    mutate(my_label = str_replace_all(my_label, 'Hfpp3', 'HFPP') ) %>%
    mutate(my_label = str_replace_all(my_label, 'Do_mg_l', 'Oxygen')) %>%
    mutate(my_label = str_replace_all(my_label, 'Annualrain', 'Rainfall')) %>%
    mutate(my_label = str_replace_all(my_label, 'Flsh', 'Flashiness')) %>%
    mutate(my_label = str_replace_all(my_label, 'No3n', 'Nitrate')) %>%
    mutate(my_label = str_replace_all(my_label, 'Ortho-p', 'Phosphate')) %>%
    mutate(my_label = str_replace_all(my_label, 'Depth_mx', 'Max Depth')) %>%
    mutate(my_label = str_replace_all(my_label, 
                                      'Canopy_density_mid', 'Canopy')) %>%
    mutate(my_label = str_replace_all(my_label, 'Lfpp', 'LFPP')  )
  
  # ---------------------------------------------------------------------------
  # environmental Plot
  ggplot() +
    #geom_rect(aes(ymin=axis2_lwr, ymax=axis2_upr,
    #              xmin=axis1_lwr, xmax=axis1_upr,
    #              fill=annualrain),
    #          data= mycent_alltime, 
    #          color=NA, alpha = .25) +
    stat_ellipse(data = sites_long,
                 aes(x=axis1, y=axis2, fill = as.factor(annualrain)),
                 geom='polygon', alpha=.2, level = 0.9,show.legend = F)+
    geom_label(aes(label=annualrain_label,
                   x=axis1_mu, y=axis2_mu, fill=as.factor(annualrain)),
               data= labs_alltime, ) +
    geom_point(data=species_long,
               aes(x=axis1, y=axis2), 
               fill = 'white', shape = 24, size = 2) +
    geom_segment(data=RDA_ev,
                 aes(x=0, y=0, xend=r^2*axis1, yend=r^2*axis2),
                 colour="black", size=1, 
                 arrow=arrow(length=unit(0.1, "inches"),
                             type='closed')) +
    geom_label_repel(
      data=RDA_ev,
      aes(x=r^2*axis1, y=r^2*axis2, label=my_label),
      color="white", fill = 'grey15', box.padding = .9,
      max.overlaps = 15) +
    xlab(axis_long[1, "label"]) +
    ylab(axis_long[2, "label"]) +
    scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_fill_manual(values = my_colors) +
    scale_color_manual(values=my_colors) +
    # paletteer::scale_fill_paletteer_c("grDevices::Zissou 1", direction=-1) +
    # paletteer::scale_color_paletteer_c("grDevices::Zissou 1", direction =-1) +
    coord_fixed(ratio=1) +
    theme_dark(base_size = 12) +
    theme(legend.position = 'none')
}

#------------------------------------------------------------------------------
# RDA time trace
#------------------------------------------------------------------------------

RDA_timetrack <- function(rda_out, my_before, my_after) {
  
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble()
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()
  
  # ---------------------------------------------------------------------------
  # plot
  sites_long %>%
    filter(collection_date < ymd(my_before) & 
             collection_date > ymd(my_after)) %>%
    ggplot() +
    geom_path(aes(x=axis1*.98, y=axis2*.98, color = as.factor(annualrain)),
              arrow = arrow(angle = 15, ends = "last", type = "closed"),
              linetype=2) +
    geom_label(aes(x = axis1_mu, y = axis2_mu, 
                   label = site_code, fill = as.factor(annualrain)), 
               data = labs_alltime) +
    geom_label(aes(x = axis1, y = axis2, 
                   label = months_to_hh, fill = as.factor(annualrain))) +
    scale_color_manual(values = my_colors) +
    scale_fill_manual(values = my_colors) +
    theme_dark(base_size = 12) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    theme(legend.position = 'none')
}

#------------------------------------------------------------------------------
# Figures: Count-Based
#------------------------------------------------------------------------------
RDA_C <- my_rda(d_env = env_filter(DC),
               d_spec = spec_filter((DC)))

RDA_C_spe <-  RDA_C %>%
  RDA_spe()

RDA_C_spe_zoom <- RDA_C %>%
  RDA_spe() +
  ylim(c(-.2,.2)) +
  xlim(c(-.2,.2)) 

RDA_C_env <- RDA_C %>%
  RDA_env()

RDA_C_time_1 <- RDA_C %>%
  RDA_timetrack(my_before = '2018-03-01', my_after = '2017-01-01')

RDA_C_time_2 <- RDA_C %>%
  RDA_timetrack(my_before = '2018-09-01', my_after = '2018-03-01') 

RDA_C_time_3 <- RDA_C %>%
  RDA_timetrack(my_before = '2021-01-01', my_after = '2020-01-01')

#------------------------------------------------------------------------------
# Figures: Biomass-Based
#------------------------------------------------------------------------------
RDA_B <- my_rda(d_env = env_filter(DB),
                d_spec = spec_filter((DB)))

# Biomass-Based species
RDA_B_spe <- RDA_B %>%
  RDA_spe()

RDA_B_spe_zoom <- RDA_B %>%
  RDA_spe() +
  ylim(c(-.2,.2)) +
  xlim(c(-.2,.2))

RDA_B_env <- RDA_B %>%
  RDA_env()

RDA_B_time_1 <- RDA_B %>%
  RDA_timetrack(my_before = '2018-03-01', my_after = '2017-01-01') 

RDA_B_time_2 <- RDA_B %>%
  RDA_timetrack(my_before = '2018-09-01', my_after = '2018-03-01') 

RDA_B_time_3 <- RDA_B %>%
  RDA_timetrack(my_before = '2021-01-01', my_after = '2020-01-01') 

#------------------------------------------------------------------------------
# RDA caption

RDA_caption <- "Redundancy Analysis axes are labeled with the proportion of variation within the community matrix is explained. The ordination is constrained by environmental variables represented by labeled, black arrows. Red crosses represent species; common species are in the middle and species that distinguish one community from another are labeled. Circles represent communities, colored by annual precipitation."

#------------------------------------------------------------------------------
# table_RDA_f
#------------------------------------------------------------------------------

table_RDA_f_caption <- "Axes values (in radians), correlation coefficients and p vlaues for fitted vectors of environmental variables and influential taxa in the Redundancy Analysis (RDA) of fish communities."

#------------------------------------------------------------------------------
# tables: Count-Based
#------------------------------------------------------------------------------

# Count-Based
table_RDA_C <- my_rda(d_env = env_filter(DC),
                d_spec = spec_filter((DC)))[[6]]

table_RDA_C_17 <- my_rda(d_env = env_filter(DC_17),
                   d_spec = spec_filter((DC_17)))[[6]]

table_RDA_C_18 <- my_rda(d_env = env_filter(DC_18),
                   d_spec = spec_filter((DC_18)))[[6]]

table_RDA_C_20 <- my_rda(d_env = env_filter(DC_20),
                   d_spec = spec_filter((DC_20)))[[6]]

#------------------------------------------------------------------------------
# tables: Biomass-Based
#------------------------------------------------------------------------------

# Biomass-Based
table_RDA_B <- my_rda(d_env = env_filter(DB),
                d_spec = spec_filter((DB)))[[6]]

table_RDA_B_17 <- my_rda(d_env = env_filter(DB_17),
                   d_spec = spec_filter((DB_17)))[[6]]

table_RDA_B_18 <- my_rda(d_env = env_filter(DB_18),
                   d_spec = spec_filter((DB_18)))[[6]]

table_RDA_B_20 <- my_rda(d_env = env_filter(DB_20),
                   d_spec = spec_filter((DB_20)))[[6]]

#------------------------------------------------------------------------------
# Clean up
#------------------------------------------------------------------------------
rm( bm, d100, DB, DB_17, DB_18, DB_20, DC, DC_17, DC_18, DC_20,
    lte, ste, RDA_C, RDA_B)

# End RDA_figures