# Ordinations
# Sean Kinard
# 2023-02-27

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------

library(tidyverse) # all tidyverse packages
library(lubridate) # date managment
library(vegan)
library(ggdark)
library(vegan)
library(BiodiversityR)
library(car)
library(paletteer)
library(ggsignif)
library(patchwork)
library(knitr)
library("ggpmisc")
library(ggrepel)
library(kableExtra)
library(ggpubr)
library(ggbiplot)

# load data
source('R_Scripts/000_d_dataframes.R')

# -----------------------------------------------------------------------------
# Pre-Processing Data
# -----------------------------------------------------------------------------

# presence or absence
d_present <- d_density %>%
  select(d100_spe, site_code, collection_date, lowest_taxon) %>%
  pivot_wider(names_from=lowest_taxon, 
              values_from=d100_spe,
              values_fill=0) %>%
  pivot_longer(cols=contains(' '), names_to='lowest_taxon', values_to='d100') %>%
  mutate(present = ifelse(d100>0, 1, 0)) 

# Probability of Occurance 
prob_occur <- d_present %>%
  group_by(lowest_taxon, site_code) %>%
  dplyr::summarize(prob_present = sum(present / length(present)))

# Rare species
rare_species <- d_present %>% 
  group_by(lowest_taxon) %>%
  dplyr::summarize(total_occurances = sum(present)) %>%
  arrange(total_occurances) %>% 
  filter(total_occurances < 5) %>%
  pull(lowest_taxon)

# RDA Preparation: Species
d_spe <- d_biomass %>%
  filter(! lowest_taxon %in% rare_species) %>%
  mutate(UID = paste(site_code, collection_date, sep='_')) %>%
  select(B100_sum_spe, lowest_taxon, UID) %>%
  pivot_wider(names_from=lowest_taxon,
              values_from=B100_sum_spe, 
              values_fill = 0) %>%
  column_to_rownames(var="UID")

# RDA preparation: Environment
RDA_evars <- c('annualrain', 'total_algae',
               'gravel', 'silt', 'canopy_density_mid', 
               'conductivity', 'no3n', 
               'med', 'rsd', 'DS', 'FS', 'HFPP7')
d_predictors <- d_environment %>%
  mutate(total_algae = sum(green_algae, diatoms,bluegreen_cyano)) %>%
  mutate(UID = paste(site_code, collection_date, sep='_')) %>%
  select(UID, any_of(RDA_evars)) %>%
  dplyr::rename(Rain=annualrain, Algae=total_algae,
         Gravel=gravel, Silt=silt, Canopy=canopy_density_mid,
         'Cond.'=conductivity, Nitrate=no3n,
         'Base.F'=med, 'Var.F'=rsd, Drought=DS, Flood=FS, 'High.F%'=HFPP7) %>%
  column_to_rownames("UID")

# ------------------------------------------------------------------------------
# RDA Calculations
#------------------------------------------------------------------------------
# function runs RDA and creates a list of data frames for plots and tables
my_rda <- function(d_env, d_spec) {
  # step 1: The ordiplot object is obtained from the result of via function rda. The ordination is done with a community data set that is transformed by the Hellinger method.
  # script generated by the BiodiversityR GUI from the constrained ordination menu
  fish_hell <- disttransform(d_spec, method='hellinger')
  Ord_model <- rda(fish_hell ~ . ,data=d_env, scaling="species")
  # This can be plotted via ordiplot
  plot2 <- ordiplot(Ord_model, choices=c(1,2))
  #------------------------------------------------------------------------------
  # Step 2 : To plot data via ggplot2
  # Extract information on the locations of sites (circles in the ordiplot)
  sites_long <- sites.long(plot2, env.data=d_env) %>%
    mutate(site_code = substr(rownames(d_env), 1,2),
           collection_date = substr(rownames(d_env), 4,13),
           collection_date = ymd(collection_date),
           cd = collection_date) %>%
    separate(cd, into=c('year', 'month', 'day'), sep='-')
  # Extract species info
  species_long <- species.long(plot2) %>%
    as_tibble() %>%
    mutate(labels = str_replace_all(labels, '\\..', '.'))
  # Information on the labeling of the axes is obtained with function axis.long. This information is extracted from the ordination model and not the ordiplot, hence it is important to select the same axes via argument 'choices'. The extracted information includes information on the percentage of explained variation. Be advised to cross-check with the summary of the redundancy analysis, where information on proportion explained is given.
  axis_long <- axis.long(Ord_model, choices=c(1, 2))
  #------------------------------------------------------------------------------
  # fit species vectors
  spp_fit <- envfit(plot2, env=fish_hell)
  df_spp_fit <- data.frame(r=spp_fit$vectors$r, p=spp_fit$vectors$pvals)
  spec_vector_long <- species.long(plot2, spec.data=df_spp_fit)
  RDA_sv <- spec_vector_long[spec_vector_long$p < 0.05, ] %>%
    as_tibble() %>% mutate(labels = str_replace_all(labels, '\\..', '.'))
  
  # fit environmental vectors
  vectors.envfit <- envfit(plot2, env= d_env)
  vectors.long2 <- filter(vectorfit.long(vectors.envfit), p < 0.05)
  RDA_ev <- vectors.long2[vectors.long2$p <= 0.05, ]
  #------------------------------------------------------------------------------
  # Table
  RDA_table <- species_long %>%
    dplyr::rename(vector = labels) %>%
    full_join(vectors.long2) %>% 
    filter(p < 0.05) %>%
    mutate(r = round(r, 3),
           p = round(p, 3),
           axis1 = round(axis1, 3),
           axis2 = round(axis2, 3)) %>%
    select(vector, r, p, axis1, axis2) %>%
    dplyr::rename('p-value'=p, 'Axis-1'=axis1, 'Axis-2'=axis2, Vector=vector)
  
  # ---------------------------------------------------------------------------
  # Format time variables
  sites_long <- sites_long %>%
    mutate(cd2 = collection_date) %>%
    separate(cd2, into = c('year', 'month', 'day')) %>%
    mutate(year=as.numeric(year),
           month=as.numeric(month),
           day=as.numeric(day)) %>%
    mutate(nday=month*30+day) %>%
    mutate(qtr = ifelse(month < 4, 'Q1',
                        ifelse(month > 3 & month < 7, 'Q2',
                               ifelse(month > 6 & month < 10, 'Q3', 'Q4')))) %>%
    mutate(days_to_hh = 
             as.numeric(as_date(collection_date) - ymd('2017-08-27')) ) %>%
    mutate(weeks_to_hh = ceiling(days_to_hh/7),
           months_to_hh = round(days_to_hh/30, 0)) %>%
    mutate(site_week_label = paste(site_code, weeks_to_hh, sep="-"))
  # -----------------------------------------------------------------------
  # Calculate all-time centroid for each site
  mycent_alltime <-  sites_long %>%
    group_by(Rain) %>%
    dplyr::summarize(axis1_mu = mean(axis1),
                     axis2_mu = mean(axis2),
                     axis1_upr = quantile(axis1, probs=.9),
                     axis1_lwr = quantile(axis1, probs=.1),
                     axis2_upr = quantile(axis2, probs=.9),
                     axis2_lwr = quantile(axis2, probs=.1))
  
  labs_alltime <- mycent_alltime %>%
    select(Rain, axis1_mu, axis2_mu) %>%
    left_join(sites_long %>%
                select(Rain, site_code)) %>%
    mutate(Rain_label = paste(round(Rain, 0), 'mm', sep=' ')) %>%
    unique()
  # -----------------------------------------------------------------------
  # centroid distance
  centroid_distance <- sites_long %>%
    as_tibble() %>%
    select(site_code, Rain, collection_date, axis1, axis2) %>%
    left_join( mycent_alltime %>% select(Rain, axis1_mu, axis2_mu) ) %>%
    mutate(dif_x1 = axis1-axis1_mu,
           dif_x2 = axis2-axis2_mu,
           centroid_dist = sqrt(dif_x1^2 + dif_x2^2)) %>%
    select(site_code, collection_date, centroid_dist)
  # -----------------------------------------------------------------------
  RDA_out <- list(axis_long = axis_long,
                  sites_long = sites_long,
                  species_long = species_long,
                  RDA_ev = RDA_ev,
                  RDA_sv = RDA_sv,
                  RDA_table = RDA_table,
                  mycent_alltime = mycent_alltime,
                  labs_alltime = labs_alltime,
                  centroid_distance = centroid_distance)
  
  return(RDA_out) }

#------------------------------------------------------------------------------
# RDA species plot function
#------------------------------------------------------------------------------
# With an ordination via redundancy analysis, the positions of species should be interpreted as arrows. It is straightforward to show the positions of the species as arrows. However, with a large number of species, it is better to reduce the number to those that explain more of the variation among the sites. This information is obtained with the envfit function of vegan.

RDA_spe <- function(rda_out) {
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble()
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()
  
  # -----------------------------------------------------------------------
  # Species Plot
  ggplot() +
    stat_ellipse(data = sites_long,
                 aes(x=axis1, y=axis2, fill = as.factor(Rain)),
                 geom='polygon', alpha=.2, level = 0.9,show.legend = F) +
    stat_ellipse(data = sites_long,
                 aes(x=axis1, y=axis2, color = as.factor(Rain)),
                 alpha=.7, level = 0.9, show.legend = F) +
    #geom_rect(aes(ymin=axis2_lwr, ymax=axis2_upr,
    #              xmin=axis1_lwr, xmax=axis1_upr,
    #              fill=Rain),
    #          data= mycent_alltime, 
    #          color=NA, alpha = .25) +
    geom_point(data=species_long,
               aes(x=axis1, y=axis2), 
               color = 'white', fill='black', shape = 24, size = 2) +
    geom_label_repel(data=RDA_sv,
                     aes(x=axis1, y=axis2, label=labels),
                     colour="white", fill = 'grey15', box.padding = .9,
                     max.overlaps = 15) +
    geom_label(aes(label=Rain_label,
                   x=axis1_mu, y=axis2_mu, fill = as.factor(Rain)),
               data= labs_alltime, show.legend=T, color ='black' ) +
    xlab(axis_long[1, "label"]) +
    ylab(axis_long[2, "label"]) +
    scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_fill_manual(values = my_colors) +
    scale_color_manual(values=my_colors) +
    #paletteer::scale_fill_paletteer_c("grDevices::Zissou 1", direction=-1) +
    #paletteer::scale_color_paletteer_c("grDevices::Zissou 1", direction =-1) +
    coord_fixed(ratio=1) +
    dark_theme_grey(base_size = 12) +
    theme(legend.position = 'none')
}

#------------------------------------------------------------------------------
# RDA environment plot function
#------------------------------------------------------------------------------
RDA_env <- function(rda_out) {
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble()
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()
  
  # ---------------------------------------------------------------------------
  # environmental Plot
  ggplot() +
    #geom_rect(aes(ymin=axis2_lwr, ymax=axis2_upr,
    #              xmin=axis1_lwr, xmax=axis1_upr,
    #              fill=Rain),
    #          data= mycent_alltime, 
    #          color=NA, alpha = .25) +
    #stat_ellipse(data = sites_long,
                 #aes(x=axis1, y=axis2, fill = as.factor(Rain)),
                 #geom='polygon', alpha=.1, level = 0.9,show.legend = F) +
    #stat_ellipse(data = sites_long,
                 #aes(x=axis1, y=axis2, color = as.factor(Rain)),
                 #alpha=.5, level = 0.9, show.legend = F) +
  geom_segment(data=RDA_ev,
               aes(x=0, y=0, xend=r^2*axis1, yend=r^2*axis2),
               colour="grey90", linewidth=.5, 
               arrow=arrow(length=unit(0.1, "inches"),
                           type='open')) +
    geom_label(aes(label=Rain_label,
                   x=axis1_mu, y=axis2_mu, fill = as.factor(Rain)),
               data= labs_alltime, show.legend=T, color ='black' ) +
    #geom_point(data=species_long,
                #aes(x=axis1, y=axis2), 
                #color = 'white', fill='black', shape = 24, size = 2) +
    
    geom_text_repel(
      data=RDA_ev,
      aes(x=r^2*axis1, y=r^2*axis2, label=vector),
      color="white", fill = 'grey15', box.padding = .9,
      max.overlaps = 15) +
    xlab(axis_long[1, "label"]) +
    ylab(axis_long[2, "label"]) +
    scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_fill_manual(values = my_colors) +
    scale_color_manual(values=my_colors) +
    # paletteer::scale_fill_paletteer_c("grDevices::Zissou 1", direction=-1) +
    # paletteer::scale_color_paletteer_c("grDevices::Zissou 1", direction =-1) +
    coord_fixed(ratio=1) +
    dark_theme_grey(base_size = 12) +
    theme(legend.position = 'none')
}

#------------------------------------------------------------------------------
# RDA time trace
#------------------------------------------------------------------------------
RDA_timetrack <- function(rda_out, my_before, my_after) {
  
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble()
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()
  
  # ---------------------------------------------------------------------------
  # plot
  sites_long %>%
    filter(collection_date < ymd(my_before) & 
             collection_date > ymd(my_after)) %>%
    ggplot() +
    geom_text_repel(data=RDA_sv,
               aes(x=axis1, y=axis2, label=labels),
               color="grey85", parse=T) +
    geom_path(aes(x=axis1*.97, y=axis2*.95, color = as.factor(Rain)),
              arrow = arrow(length = unit(0.2, "inches"),
                            angle = 15, ends = "last", type = "closed"),
              linetype=1) +
    geom_label(aes(x = axis1, y = axis2, label = months_to_hh, 
                   color = as.factor(Rain)), fill = 'black') +
    geom_label(aes(x = axis1_mu, y = axis2_mu, 
                   label = Rain_label, fill = as.factor(Rain)), 
               color = 'black', data = labs_alltime) +
    scale_color_manual(values = my_colors) +
    scale_fill_manual(values = my_colors) +
    dark_theme_grey(base_size = 12) +
    xlab(element_blank()) +
    ylab(element_blank()) +
    theme(legend.position = 'none')
}

#------------------------------------------------------------------------------
# Figures: Biomass-Based (2017, 2018, 2020)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# RDA Calculations
#------------------------------------------------------------------------------
rda_all <- my_rda(d_env = d_predictors,
             d_spec = d_spe)

rda_all_spe <-  rda_all %>% RDA_spe()

rda_all_env <- rda_all %>% RDA_env()

rda_all_time_1 <- rda_all %>%
  RDA_timetrack(my_before = '2018-03-01', my_after = '2017-01-01')

rda_all_time_2 <- rda_all %>%
  RDA_timetrack(my_before = '2018-09-01', my_after = '2018-03-01') 

rda_all_time_3 <- rda_all %>%
  RDA_timetrack(my_before = '2021-01-01', my_after = '2020-01-01')

#------------------------------------------------------------------------------
# Figures: Biomass-Based (2017-2018)
#------------------------------------------------------------------------------
trim_dates <- function(my_data, after, before) {
  my_data %>%
    rownames_to_column('site_date') %>%
    as_tibble() %>%
    separate(site_date, into=c('site_code', 'collection_date'), sep='_') %>%
    mutate(collection_date = ymd(collection_date)) %>%
  filter(collection_date > ymd(after) &
           collection_date < ymd(before)) %>%
    mutate(UID = paste(site_code, collection_date, sep = '_')) %>%
    select(!c(site_code, collection_date)) %>%
    column_to_rownames('UID')
}


d_predictors_1718 <- trim_dates(d_predictors, '2017-01-01', '2019-01-01')
d_spe_1718 <- trim_dates(d_spe, '2017-01-01', '2019-01-01')

rda_1718 <- my_rda(d_env = d_predictors_1718,
                  d_spec = d_spe_1718)

rda_1718_spe <-  rda_1718 %>% RDA_spe()

rda_1718_env <- rda_1718 %>% RDA_env()

rda_1718_time_1 <- rda_1718 %>%
  RDA_timetrack(my_before = '2018-03-01', my_after = '2017-01-01')

rda_1718_time_2 <- rda_1718 %>%
  RDA_timetrack(my_before = '2018-09-01', my_after = '2018-03-01') 

#------------------------------------------------------------------------------
# Figures: Biomass-Based (2020)
#------------------------------------------------------------------------------
d_predictors_2020 <- trim_dates(d_predictors, '2020-01-01', '2021-01-01')
d_spe_2020 <- trim_dates(d_spe, '2020-01-01', '2021-01-01')

rda_2020 <- my_rda(d_env = d_predictors_2020,
                   d_spec = d_spe_2020)

rda_2020_spe <-  rda_2020 %>% RDA_spe()

rda_2020_env <- rda_2020 %>% RDA_env()

rda_2020_time_3 <- rda_2020 %>%
  RDA_timetrack(my_before = '2021-01-01', my_after = '2020-01-01')

#------------------------------------------------------------------------------
# Export
#------------------------------------------------------------------------------
d_axis <- rda_all$sites_long %>%
  as_tibble() %>%
  select(axis1, axis2, any_of(my_index)) %>%
  mutate(collection_date = as_date(collection_date))

d_biovars <- d_axis %>% 
  right_join(read_csv('Data/d_biovars.csv'))

write_csv(d_axis, 'Data/d_axis.csv')
write_csv(d_biovars, 'Data/d_biovars.csv')

# All dates
#ggsave('Figures/rda_all_spe.pdf',
#       plot = rda_all_spe,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_all_env.pdf',
#       plot = rda_all_env,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_all_time_1.pdf',
#       plot = rda_all_time_1,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_all_time_2.pdf',
#       plot = rda_all_time_2,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_all_time_3.pdf',
#       plot = rda_all_time_3,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
# 2017 and 2018
#ggsave('Figures/rda_1718_spe.pdf',
#       plot = rda_1718_spe,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_1718_env.pdf',
#       plot = rda_1718_env,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_1718_time_1.pdf',
#       plot = rda_1718_time_1,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_1718_time_2.pdf',
#       plot = rda_1718_time_2,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
# 2020
#ggsave('Figures/rda_2020_spe.pdf',
#       plot = rda_2020_spe,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_2020_env.pdf',
#       plot = rda_2020_env,
#       width = 9,
#       height = 9,
#       units = c("in"))
#
#ggsave('Figures/rda_2020_time_3.pdf',
#       plot = rda_2020_time_3,
#       width = 9,
#       height = 9,
#       units = c("in"))
#------------------------------------------------------------------------------
# End Ordination